create database stocks;
use stocks;

-- task 3
-- inner join for order details
-- join order,order_items,and products to display detailed line items.


select o.order_id,o.order_date,oi.item_id,p.product_name,oi.quantity,oi.list_price,oi.discount from orders o
inner join order_items oi on o.order_id=oi.order_id
inner join products p on oi.product_id=p.Product_id;

-- task 4
-- total sales by store
-- write a query to group sales(total_price) by each store_id.


SELECT s.store_id,s.store_name,SUM((oi.list_price * oi.quantity) - oi.discount) AS total_sales FROM stores s
INNER JOIN orders o ON s.store_id = o.store_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.store_id, s.store_name
ORDER BY total_sales DESC;


-- task 5 
-- Top 5 Selling Products  
-- Use ORDER BY and LIMIT to get the top 5 most sold products by  quantity.  


SELECT p.product_id,p.product_name,SUM(oi.quantity) AS total_quantity_sold FROM products p
INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

-- task 6
-- Customer Purchase Summary  
-- For each customer, return total orders placed, total items purchased,  and total revenue.  


SELECT c.customer_id,CONCAT(c.first_name, ' ', c.last_name) AS customer_name,COUNT(DISTINCT o.order_id) AS total_orders,SUM(oi.quantity) AS total_items_purchased,
SUM((oi.list_price * oi.quantity) - oi.discount) AS total_revenue
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, customer_name
ORDER BY total_revenue DESC;


-- task 7
-- Segment Customers by Total Spend  
-- Write a query to classify customers into spending brackets (e.g., low,  medium, high).  

SELECT c.customer_id,CONCAT(c.first_name, ' ', c.last_name) AS customer_name,SUM((oi.list_price * oi.quantity) - oi.discount) AS total_spend,
CASE WHEN SUM((oi.list_price * oi.quantity) - oi.discount) < 5000 THEN 'Low'WHEN SUM((oi.list_price * oi.quantity) - oi.discount) BETWEEN 5000 AND 15000 THEN 'Medium'
ELSE 'High'END AS spending_segment FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, customer_name
ORDER BY total_spend DESC;

-- task 8
-- Staff Performance Analysis  
-- Analyze total revenue generated by each staff member based on their  handled orders.


SELECT s.staff_id,CONCAT(s.first_name, ' ', s.last_name) AS staff_name,COUNT(DISTINCT o.order_id) AS total_orders,SUM((oi.list_price * oi.quantity) - oi.discount) AS total_revenue
FROM staffs s
INNER JOIN orders o ON s.staff_id = o.staff_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.staff_id, staff_name
ORDER BY total_revenue DESC;


-- task 9
-- Stock Alert Query  
-- Write a query to list products where stock quantity < 10 in any store.  



SELECT s.store_id,st.store_name,p.product_id,p.product_name,s.quantity AS stock_quantity FROM stocks s
INNER JOIN products p ON s.product_id = p.product_id
INNER JOIN stores st ON s.store_id = st.store_id
WHERE s.quantity < 10
ORDER BY s.quantity ASC;


-- task 10
--  Create Final Segmentation Table  
-- Create a table customer_segments that will be populated from Python  ML results later.  

CREATE TABLE customer_segments (customer_id INT PRIMARY KEY,recency INT,frequency INT,monetary DECIMAL(10,2),segment VARCHAR(50));
